name: Handle issue
on: issues              #run when an issue we have created manually
jobs: 
  output-info:
    runs-on: ubuntu-latest
    steps: 
      - name: output event details
        run: echo "${{ toJSON(github.event) }}"
       